module:
  action: 0
  address: 0
  asset_injector: 0
  auto_entitylabel: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  captcha: 0
  ckeditor: 0
  ckeditor_media_embed: 0
  ckeditor_templates: 0
  color: 0
  comment: 0
  config: 0
  config_partial_export: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  custom_module: 0
  date_popup: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_type_clone: 0
  extra_image_field_classes: 0
  facets: 0
  feeds: 0
  feeds_tamper: 0
  fences: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_browser: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  focal_point: 0
  geolocation: 0
  google_analytics: 0
  google_cse: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  kwall_map: 0
  kwall_migrate: 0
  kwall_site_alert: 0
  kwalladmincustomcode: 0
  language: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_class: 0
  linkit: 0
  mailsystem: 0
  masquerade: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_scheduler: 0
  migrate_source_csv: 0
  migrate_tools: 0
  module_filter: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  rest: 0
  restui: 0
  rules: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_solr: 0
  sendgrid_integration: 0
  serialization: 0
  shortcut: 0
  smart_ip: 0
  smart_ip_maxmind_geoip2_bin_db: 0
  smtp: 0
  svg_image: 0
  system: 0
  tamper: 0
  taxonomy: 0
  tb_megamenu: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_link_attributes: 0
  twig_vardumper: 0
  typed_data: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_block_area: 0
  views_bulk_operations: 0
  views_templates: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  wysiwyg_template: 0
  wysiwyg_template_core: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  linked_field: 100
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  kwall: 0
  onu: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
