apikey: abc123
test_defaults:
  to: b-paris@onu.edu
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: 'ONU website'
  to_name: Brian
  reply_to: do_not_reply@onu.edu
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
