smtp_on: true
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: OhioNorthernUniveristy
smtp_password: Lehr_1871
smtp_from: do_not_reply@onu.edu
smtp_fromname: 'Ohio Northern Univeristy'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
